# Generated by Django 4.2.1 on 2024-03-09 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, verbose_name='序号')),
                ('common_name', models.CharField(max_length=255, verbose_name='药品通用名称')),
                ('english_name', models.CharField(blank=True, max_length=255, verbose_name='英文名称/商品名')),
                ('specification', models.TextField(blank=True, verbose_name='规格')),
                ('dosage_form', models.CharField(blank=True, max_length=50, verbose_name='剂型')),
                ('license_holder', models.CharField(blank=True, max_length=255, verbose_name='持证商')),
                ('note1', models.CharField(blank=True, max_length=255, verbose_name='备注1')),
                ('note2', models.CharField(blank=True, max_length=255, verbose_name='备注2')),
                ('prescription_origin', models.TextField(blank=True, verbose_name='处方（原研）')),
                ('prescription_translation', models.TextField(blank=True, verbose_name='处方（翻译）')),
                ('contains_our_excipient', models.CharField(blank=True, max_length=50, verbose_name='是否含我司辅料')),
                ('excipient', models.CharField(blank=True, max_length=255, verbose_name='辅料')),
                ('dosage_form_1', models.CharField(blank=True, max_length=50, verbose_name='剂型')),
            ],
            options={
                'db_table': '仿制药参比制剂目录',
            },
        ),
    ]
