# Generated by Django 4.2.1 on 2023-12-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.CharField(blank=True, choices=[('原辅料销售部', '原辅料销售部'), ('食品添加剂部', '食品添加剂部'), ('外贸部', '外贸部'), ('研发服务部', '研发服务部'), ('产品管理部', '产品管理部'), ('内务部', '内务部'), ('信管部', '信管部')], max_length=255, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(blank=True, choices=[], max_length=255, verbose_name='职位'),
        ),
    ]
