# Generated by Django 4.2.1 on 2023-11-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overdue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('transaction_date', models.DateField(verbose_name='交易日期')),
                ('province', models.CharField(max_length=255, verbose_name='省份')),
                ('customer_name', models.CharField(max_length=255, verbose_name='客户名称')),
                ('salesperson', models.CharField(max_length=255, verbose_name='业务员')),
                ('accounts_receivable', models.CharField(max_length=255, verbose_name='应收账款')),
                ('accounts_receivable_due_date', models.DateField(verbose_name='应收账款期限')),
                ('repayment_date', models.DateField(verbose_name='还款日')),
                ('received_payment_1', models.CharField(max_length=255, verbose_name='已收货款1')),
                ('received_payment_2', models.CharField(max_length=255, verbose_name='已收货款2')),
                ('accounts_receivable_balance', models.CharField(max_length=255, verbose_name='应收账款余额')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('description', models.TextField(blank=True, verbose_name='逾期说明与回款计划')),
            ],
            options={
                'db_table': '逾期账款明细',
                'managed': False,
            },
        ),
    ]
