# Generated by Django 4.2.1 on 2023-11-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorization',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customerengagement',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customerflow',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='existingformulationdeveloping',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='existingformulationprogressdescription',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='existingformulationtodevelop',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='existingproductcompleted',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='foreigncustomerprofile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='foreigntradeledger',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='internaltradeledger',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='newproductcompleted',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='newproductdevelopingprogress',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='newproductdevelopment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True},
        ),
    ]
