# Generated by Django 4.2.1 on 2024-03-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foreigncustomerprofile',
            old_name='customer_profile_number',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='customerflow',
            name='initial_contact_time',
            field=models.DateField(blank=True, verbose_name='初始联系时间'),
        ),
    ]
