# Generated by Django 4.2.1 on 2023-11-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_overdue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overdue',
            options={},
        ),
    ]
