# Generated by Django 4.2.1 on 2024-03-11 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_customer_profile_number_foreigncustomerprofile_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerflow',
            old_name='customer_id',
            new_name='id',
        ),
    ]
