# Generated by Django 4.2.1 on 2023-11-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_authorization_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('work_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='工号')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='密码')),
            ],
        ),
        migrations.AlterModelOptions(
            name='authorization',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customerengagement',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customerflow',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='existingformulationdeveloping',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='existingformulationprogressdescription',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='existingformulationtodevelop',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='existingproductcompleted',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='foreigncustomerprofile',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='foreigntradeledger',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='internaltradeledger',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='newproductcompleted',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='newproductdevelopingprogress',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='newproductdevelopment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False},
        ),
    ]
