# Generated by Django 4.2.1 on 2023-11-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_overdue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overdue',
            options={'managed': False},
        ),
    ]
