# Generated by Django 4.2.1 on 2024-03-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_customeraudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraudit',
            name='application_date',
            field=models.DateField(blank=True, verbose_name='申请日期'),
        ),
        migrations.AlterField(
            model_name='customeraudit',
            name='audit_date',
            field=models.DateField(blank=True, verbose_name='审计日期'),
        ),
        migrations.AlterField(
            model_name='customeraudit',
            name='audit_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='审计类型'),
        ),
        migrations.AlterField(
            model_name='customeraudit',
            name='audit_variety',
            field=models.TextField(blank=True, verbose_name='审计品种'),
        ),
        migrations.AlterField(
            model_name='customeraudit',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='customeraudit',
            name='month',
            field=models.DateField(blank=True, verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='customeraudit',
            name='received_audit_letter',
            field=models.BooleanField(blank=True, verbose_name='是否收到审计函'),
        ),
        migrations.AlterField(
            model_name='customeraudit',
            name='sales_manager',
            field=models.CharField(blank=True, max_length=100, verbose_name='销售经理'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='amount_ten_thousand',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='金额（万元）'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='budget_category',
            field=models.TextField(blank=True, verbose_name='预算分类'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='check_price',
            field=models.IntegerField(blank=True, verbose_name='核对单价'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='company_category',
            field=models.CharField(blank=True, max_length=50, verbose_name='企业分类'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='企业名称'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='customer_level',
            field=models.CharField(blank=True, max_length=10, verbose_name='客户级别'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='销售部'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='formulation_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='制剂项目名称'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='quantity_kg',
            field=models.IntegerField(blank=True, verbose_name='数量（KG）'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='specification_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='规格编码'),
        ),
        migrations.AlterModelTable(
            name='products',
            table='1药用辅料产品规格编码设置表-2022.08.18',
        ),
    ]
