# Generated by Django 4.2.1 on 2023-11-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_admin_alter_authorization_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
