# Generated by Django 4.2.1 on 2024-03-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_customer_id_customerflow_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerengagement',
            old_name='engagement_number',
            new_name='id',
        ),
    ]
