# Generated by Django 4.2.1 on 2023-11-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_overdue_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foreign_receivable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('transaction_date', models.DateField(verbose_name='交易日期')),
                ('customer_name', models.CharField(max_length=255, verbose_name='客户名称')),
                ('salesperson', models.CharField(max_length=255, verbose_name='业务员')),
                ('accounts_receivable_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应收账款-USD')),
                ('accounts_receivable_rmb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应收账款-人民币')),
                ('accounts_receivable_due', models.DateField(verbose_name='应收账款期限')),
                ('repayment_date', models.DateField(verbose_name='还款日')),
                ('received_payment1_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='已收货款1-USD')),
                ('received_payment1_rmb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='已收货款1-人民币')),
                ('received_payment2_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='已收货款2-USD')),
                ('received_payment2_rmb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='已收货款2-人民币')),
                ('accounts_receivable_balance_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应收账款余额-USD')),
                ('accounts_receivable_balance_rmb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应收账款余额-人民币')),
                ('rmb_discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='折人民币')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'db_table': '外贸部收款明细',
                'managed': False,
            },
        ),
    ]
