# Generated by Django 4.2.1 on 2024-03-10 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_customeraudit_application_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authorization',
            table='授权书总表-2022.08',
        ),
        migrations.AlterModelTable(
            name='customerprofile',
            table='研发服务部客户档案表',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='产品问题反馈表20230307',
        ),
        migrations.AlterModelTable(
            name='foreigncustomerprofile',
            table='外贸部客户档案表模板202303',
        ),
        migrations.AlterModelTable(
            name='foreigntradeledger',
            table='外贸部台账总表',
        ),
        migrations.AlterModelTable(
            name='internaltradeledger',
            table='内贸部台账总表',
        ),
        migrations.AlterModelTable(
            name='products',
            table='药用辅料产品规格编码设置表-2022.08.18',
        ),
    ]
