# Generated by Django 4.2.1 on 2023-11-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('province', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=200)),
                ('salesperson', models.CharField(max_length=100)),
                ('receivable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receivable_due_date', models.DateField(blank=True, null=True)),
                ('repayment_date', models.DateField(blank=True, null=True)),
                ('received_amount1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('received_amount2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receivable_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '账款明细',
                'managed': False,
            },
        ),
    ]
