# Generated by Django 4.2.1 on 2024-03-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_authorization_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraudit',
            name='received_audit_letter',
            field=models.CharField(blank=True, max_length=10, verbose_name='是否收到审计函'),
        ),
        migrations.AlterField(
            model_name='customerflow',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='客户编号'),
        ),
    ]
