# Generated by Django 4.2.1 on 2023-12-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_foreign_receivable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('actual_jan', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='1月实际回款')),
                ('actual_feb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='2月实际回款')),
                ('actual_mar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='3月实际回款')),
                ('actual_apr', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='4月实际回款')),
                ('actual_may', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='5月实际回款')),
                ('actual_jun', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='6月实际回款')),
                ('actual_jul', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='7月实际回款')),
                ('actual_aug', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='8月实际回款')),
                ('actual_sep', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='9月实际回款')),
                ('actual_oct', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='10月实际回款')),
                ('actual_nov', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='11月实际回款')),
                ('actual_dec', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='12月实际回款')),
            ],
            options={
                'db_table': '实际销售数据',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplaintSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=20, verbose_name='月份')),
                ('shipment_date', models.DateField(verbose_name='发货日期')),
                ('department', models.CharField(max_length=100, verbose_name='部门')),
                ('complaint_type', models.CharField(max_length=100, verbose_name='客诉问题类型')),
                ('form_type', models.CharField(max_length=100, verbose_name='表单类型')),
                ('contract_number', models.CharField(max_length=100, verbose_name='合同编号')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('specification', models.CharField(max_length=100, verbose_name='规格')),
                ('replacement_quantity', models.FloatField(verbose_name='补/换货数量（KG）')),
                ('reason', models.TextField(verbose_name='原因')),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='分类')),
                ('remarks', models.TextField(verbose_name='备注（补/换货运单号）')),
                ('return_history', models.TextField(verbose_name='退货记录')),
            ],
            options={
                'db_table': '全国客诉汇总',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sales1', '销售一部'), ('sales2', '销售二部'), ('sales3', '销售三部'), ('sales4', '销售四部'), ('sales5', '销售五部'), ('sales6', '销售六部'), ('additives', '食品添加剂部'), ('rnd_service', '研发服务部'), ('foreign_trade', '外贸部')], max_length=20, unique=True)),
                ('year', models.IntegerField(verbose_name='年份')),
                ('target_jan', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='1月回款目标')),
                ('target_feb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='2月回款目标')),
                ('target_mar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='3月回款目标')),
                ('target_apr', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='4月回款目标')),
                ('target_may', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='5月回款目标')),
                ('target_jun', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='6月回款目标')),
                ('target_jul', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='7月回款目标')),
                ('target_aug', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='8月回款目标')),
                ('target_sep', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='9月回款目标')),
                ('target_oct', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='10月回款目标')),
                ('target_nov', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='11月回款目标')),
                ('target_dec', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='12月回款目标')),
            ],
            options={
                'db_table': '各部门回款目标',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesVisitReport',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('company_name', models.CharField(max_length=255, verbose_name='企业名称')),
                ('visit_date', models.DateField(verbose_name='拜访日期')),
                ('visits_this_year', models.PositiveIntegerField(verbose_name='本年度拜访次数')),
                ('customer_type', models.CharField(choices=[('new', '新客户'), ('existing', '老客户')], max_length=10, verbose_name='客户性质')),
                ('visit_nature', models.CharField(max_length=255, verbose_name='拜访性质')),
                ('visit_purpose', models.TextField(verbose_name='拜访目的')),
                ('visit_feedback', models.TextField(verbose_name='拜访结果及反馈')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'db_table': '销售客户拜访报告',
                'managed': False,
            },
        ),
    ]
