# Generated by Django 4.2.1 on 2024-03-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_customeraudit_received_audit_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='common_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='药品通用名称'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='序号'),
        ),
    ]
