# Generated by Django 4.2.1 on 2024-03-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_preparation_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparation_new',
            name='serial_number',
        ),
    ]
