# Generated by Django 4.2.1 on 2024-03-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_preparation_new_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparation_new',
            name='estimated_annual_consumption',
            field=models.CharField(blank=True, max_length=100, verbose_name='预估年用量'),
        ),
    ]
