# Generated by Django 4.2.1 on 2024-03-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_preparation_new_estimated_annual_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparation_new',
            name='before_declaration',
            field=models.CharField(blank=True, max_length=100, verbose_name='申报前'),
        ),
        migrations.AlterField(
            model_name='preparation_new',
            name='before_pilot',
            field=models.CharField(blank=True, max_length=100, verbose_name='中试前'),
        ),
        migrations.AlterField(
            model_name='preparation_new',
            name='continuous_3_batch_auxiliary_material_sampling_testing',
            field=models.CharField(blank=True, max_length=100, verbose_name='连续3批辅料小样检测'),
        ),
        migrations.AlterField(
            model_name='preparation_new',
            name='delivery',
            field=models.CharField(blank=True, max_length=100, verbose_name='发货'),
        ),
        migrations.AlterField(
            model_name='preparation_new',
            name='first_production_3_batches',
            field=models.CharField(blank=True, max_length=100, verbose_name='首次生产3批'),
        ),
        migrations.AlterField(
            model_name='preparation_new',
            name='formal_contract_signing',
            field=models.CharField(blank=True, max_length=100, verbose_name='正式合同签订'),
        ),
        migrations.AlterField(
            model_name='preparation_new',
            name='in_progress',
            field=models.CharField(blank=True, max_length=100, verbose_name='进行中'),
        ),
        migrations.AlterField(
            model_name='preparation_new',
            name='initial_negotiation',
            field=models.CharField(blank=True, max_length=100, verbose_name='前期洽谈'),
        ),
        migrations.AlterField(
            model_name='preparation_new',
            name='stability_inspection',
            field=models.CharField(blank=True, max_length=100, verbose_name='稳定性考察'),
        ),
        migrations.AlterField(
            model_name='preparation_new',
            name='supplementary_application_completion_change',
            field=models.CharField(blank=True, max_length=100, verbose_name='补充申请备案完成变更'),
        ),
        migrations.AlterField(
            model_name='preparation_new',
            name='supplier_audit',
            field=models.CharField(blank=True, max_length=100, verbose_name='供应商审计'),
        ),
        migrations.AlterField(
            model_name='preparation_new',
            name='supplier_change_request',
            field=models.CharField(blank=True, max_length=100, verbose_name='提出供应商变更申请'),
        ),
    ]
