# Generated by Django 4.2.1 on 2024-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_preparation_new_before_declaration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_new',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('status', models.CharField(blank=True, choices=[('开发中', '开发中'), ('进行中', '进行中'), ('已完成', '已完成')], max_length=20, verbose_name='开发状态')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='企业名称')),
                ('province', models.CharField(blank=True, max_length=255, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='城市')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='部门')),
                ('specific_department', models.CharField(blank=True, max_length=255, verbose_name='具体部门')),
                ('manager', models.CharField(blank=True, max_length=255, verbose_name='负责人')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='客户名称')),
                ('customer_source', models.CharField(blank=True, max_length=255, verbose_name='客户来源')),
                ('product', models.CharField(blank=True, max_length=255, verbose_name='产品')),
                ('specification_code', models.CharField(blank=True, max_length=255, verbose_name='规格编码')),
                ('special_requirements', models.CharField(blank=True, max_length=255, verbose_name='特殊需求')),
                ('sample_or_sale', models.CharField(blank=True, max_length=255, verbose_name='申样/销售')),
                ('is_duplicate_project', models.CharField(blank=True, max_length=255, verbose_name='是否重复项目')),
                ('initial_quote', models.CharField(blank=True, max_length=255, verbose_name='初次报价')),
                ('quantity', models.CharField(blank=True, max_length=255, verbose_name='数量')),
                ('unit_price', models.CharField(blank=True, max_length=255, verbose_name='单价')),
                ('amount', models.CharField(blank=True, max_length=255, verbose_name='金额')),
                ('formulation_name', models.CharField(blank=True, max_length=255, verbose_name='制剂名称')),
                ('is_consistency_evaluation_product', models.CharField(blank=True, max_length=255, verbose_name='是否一致性评价品种')),
                ('excipient_purpose', models.CharField(blank=True, max_length=255, verbose_name='辅料用途')),
                ('prescription_quantity', models.CharField(blank=True, max_length=255, verbose_name='处方用量')),
                ('start_development_date', models.DateField(verbose_name='起始开发日期')),
                ('customer_importance', models.CharField(blank=True, max_length=255, verbose_name='客户重要程度')),
                ('excipient_inspection', models.DateField(verbose_name='辅料检验')),
                ('prescription_selection', models.DateField(verbose_name='处方筛选')),
                ('preliminary_process_validation_small_scale', models.DateField(db_column='preliminary_process_validation_small_scale', verbose_name='初步验证工艺（小试）')),
                ('pilot_scale_verification', models.DateField(verbose_name='中试验证')),
                ('process_verification', models.DateField(verbose_name='工艺验证')),
                ('clinical_trials', models.DateField(verbose_name='临床')),
                ('approval_received', models.DateField(verbose_name='拿到批文')),
                ('regular_purchase', models.DateField(verbose_name='正常采购')),
                ('response_needed', models.DateField(verbose_name='是否回复')),
                ('in_progress', models.DateField(verbose_name='进行中')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('before_pilot_scale', models.DateField(verbose_name='中试前')),
                ('before_submission', models.DateField(verbose_name='申报前')),
                ('issuance_date', models.DateField(verbose_name='开具时间')),
                ('landing_company_name', models.CharField(blank=True, max_length=255, verbose_name='落地企业名称')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='联系人')),
                ('transfer_to_sales_manager', models.DateField(verbose_name='移交销售经理')),
                ('transfer_date', models.DateField(verbose_name='移交时间')),
            ],
            options={
                'db_table': '新品开发',
            },
        ),
        migrations.DeleteModel(
            name='ExistingFormulationDeveloping',
        ),
        migrations.DeleteModel(
            name='ExistingFormulationToDevelop',
        ),
        migrations.DeleteModel(
            name='ExistingProductCompleted',
        ),
        migrations.AlterField(
            model_name='preparation_new',
            name='status',
            field=models.CharField(blank=True, choices=[('开发中', '开发中'), ('进行中', '进行中'), ('已完成', '已完成')], max_length=20, verbose_name='开发状态'),
        ),
        migrations.AlterModelTable(
            name='preparation_new',
            table='已有变更',
        ),
    ]
