# Generated by Django 4.2.1 on 2024-03-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_product_new_delete_existingformulationdeveloping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_new',
            name='approval_received',
            field=models.DateField(blank=True, verbose_name='拿到批文'),
        ),
        migrations.AlterField(
            model_name='product_new',
            name='before_pilot_scale',
            field=models.CharField(blank=True, max_length=100, verbose_name='中试前'),
        ),
        migrations.AlterField(
            model_name='product_new',
            name='before_submission',
            field=models.CharField(blank=True, max_length=100, verbose_name='申报前'),
        ),
        migrations.AlterField(
            model_name='product_new',
            name='clinical_trials',
            field=models.DateField(blank=True, verbose_name='临床'),
        ),
        migrations.AlterField(
            model_name='product_new',
            name='excipient_inspection',
            field=models.DateField(blank=True, verbose_name='辅料检验'),
        ),
        migrations.AlterField(
            model_name='product_new',
            name='in_progress',
            field=models.DateField(blank=True, verbose_name='进行中'),
        ),
        migrations.AlterField(
            model_name='product_new',
            name='issuance_date',
            field=models.CharField(blank=True, max_length=100, verbose_name='开具时间'),
        ),
        migrations.AlterField(
            model_name='product_new',
            name='pilot_scale_verification',
            field=models.DateField(blank=True, verbose_name='中试验证'),
        ),
        migrations.AlterField(
            model_name='product_new',
            name='preliminary_process_validation_small_scale',
            field=models.DateField(blank=True, db_column='preliminary_process_validation_small_scale', verbose_name='初步验证工艺（小试）'),
        ),
        migrations.AlterField(
            model_name='product_new',
            name='prescription_selection',
            field=models.DateField(blank=True, verbose_name='处方筛选'),
        ),
        migrations.AlterField(
            model_name='product_new',
            name='process_verification',
            field=models.DateField(blank=True, verbose_name='工艺验证'),
        ),
        migrations.AlterField(
            model_name='product_new',
            name='regular_purchase',
            field=models.DateField(blank=True, verbose_name='正常采购'),
        ),
        migrations.AlterField(
            model_name='product_new',
            name='response_needed',
            field=models.BooleanField(default=False, verbose_name='是否回复'),
        ),
        migrations.AlterField(
            model_name='product_new',
            name='start_development_date',
            field=models.DateField(blank=True, verbose_name='起始开发日期'),
        ),
        migrations.AlterField(
            model_name='product_new',
            name='transfer_date',
            field=models.DateField(blank=True, verbose_name='移交时间'),
        ),
        migrations.AlterField(
            model_name='product_new',
            name='transfer_to_sales_manager',
            field=models.CharField(blank=True, max_length=100, verbose_name='移交销售经理'),
        ),
    ]
