# Generated by Django 4.2.1 on 2024-03-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_product_new_approval_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('product_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_descriptions', to='management.product_new')),
            ],
            options={
                'db_table': '新品开发进度描述',
            },
        ),
    ]
