# Generated by Django 4.2.1 on 2024-03-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_progressdescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExistingFormulationProgressDescription',
        ),
        migrations.DeleteModel(
            name='NewProductCompleted',
        ),
        migrations.DeleteModel(
            name='NewProductDevelopingProgress',
        ),
        migrations.DeleteModel(
            name='NewProductDevelopment',
        ),
    ]
