# Generated by Django 4.2.1 on 2024-03-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_delete_existingformulationprogressdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('product_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PreparationDescription', to='management.preparation_new')),
            ],
            options={
                'db_table': '已有制剂开发进度描述',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('product_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductDescription', to='management.product_new')),
            ],
            options={
                'db_table': '新品开发进度描述',
            },
        ),
        migrations.DeleteModel(
            name='ProgressDescription',
        ),
    ]
