# Generated by Django 4.2.1 on 2024-03-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_preparationdescription_productdescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preparationdescription',
            old_name='product_new',
            new_name='preparation_new',
        ),
    ]
