# Generated by Django 4.2.1 on 2024-03-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_rename_product_new_preparationdescription_preparation_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internaltradeledger',
            name='first_occurrence',
        ),
        migrations.AlterField(
            model_name='foreigncustomerprofile',
            name='estimated_annual_usage',
            field=models.IntegerField(blank=True, verbose_name='预估年用量(现有供应商情况描述)'),
        ),
    ]
