# Generated by Django 4.2.1 on 2024-03-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_salesvisitreport_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesvisitreport',
            name='visits_this_year',
            field=models.IntegerField(blank=True, verbose_name='本年度拜访次数'),
        ),
    ]
