# Generated by Django 4.2.1 on 2024-03-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_alter_salesvisitreport_visits_this_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesvisitreport',
            name='customer_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='客户性质'),
        ),
    ]
