# Generated by Django 4.2.1 on 2024-03-23 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_alter_salesvisitreport_customer_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesVisitReport',
        ),
    ]
