# Generated by Django 4.2.1 on 2024-03-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_salesvisitreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesvisitreport',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('新客户', '新客户'), ('老客户', '老客户')], max_length=255, verbose_name='客户性质'),
        ),
    ]
