# Generated by Django 4.2.1 on 2024-03-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_alter_salesvisitreport_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsummary',
            name='month',
            field=models.IntegerField(blank=True, verbose_name='月份'),
        ),
    ]
